### ISSUE TITLE
Storage of locales array should be configureable

### ISSUE THREAD

**Issue by dbendy** [intesso/connect-locale#2]
I am building an app that needs full i18n support.  Because of that, my locales array that I am passing in to `connect-locale` is quite long - it includes every recognized locale in the [cldr-data](https://www.npmjs.com/package/cldr-data) project.  `connect-locale` stores that entire array every time, which appears to be wasteful.  Would it be possible to add a configuration option that allows me to turn off storing of the locales array?

**Comment by andineck** [comment]
I am not sure if I understand your question correctly. `connect-locale` does transform the `locale` Array into a `localesLookup` Object when instantiating the module, so that it is more efficient during the "middleware" request cycle. Otherwise it would have to loop over the `locale` array on every request to find a matching locale, which I think would be way less efficient.

**Comment by dbendy** [comment]
My question is whether it would be possible to change the module slightly so that it wouldn't include the `locales` array in the object that is stored in the cookie, session, etc, i.e. all the places in the `storeLocaleTo` array?

**Comment by andineck** [comment]
ah, ok, now I understand. One would have to add an option for this. https://github.com/intesso/connect-locale/blob/master/server.js#L96. Do you want to give it a try?

**Comment by dbendy** [comment]
Here you go: https://github.com/intesso/connect-locale/pull/3

**Comment by andineck** [comment]
Thx! new version is on npm 1.3.1
